version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    allow:
      - dependency-name: "*"
        dependency-type: production
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
