image: "node:lts-stretch"

before_script:
    - npm install

stages:
    - build

build:
    stage: build
    script:
        - npm run lint
        - npm run build

cache:
    paths:
        - node_modules/
