stages:
    - build
    - build-image

build:
    stage: build
    image: "node:lts-stretch"
    before_script:
        - npm install
    script:
        - npm run lint
        - npm run build
    artifacts:
        paths:
            - dist/
    cache:
        paths:
            - node_modules/

build-image:
    stage: build-image
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
        - mkdir -p /.kaniko/.docker
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    dependencies:
        - build
    only:
        - master
