include:
    - "https://gitlab.com/sokkuri/CI/-/raw/master/.gitlab/ci/publish-image.gitlab-ci.yml"

stages:
    - build
    - publish

build:
    stage: build
    image: "node:lts-stretch"
    before_script:
        - npm install
    script:
        - npm run lint
        - npm run build
    artifacts:
        paths:
            - dist/
    cache:
        paths:
            - node_modules/
