name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master, dev ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: sokkuri/code-reviewer@v1.0.1

  build:
    runs-on: ubuntu-latest
    needs: [ test ]
    container: node:lts-alpine
    steps:
      - uses: actions/checkout@v2.3.4
      - run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@v2.2.2
        with:
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: [ test, build ]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/download-artifact@v2.0.8
      - uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ secrets.SENKO_REGISTRY_USER }}
          password: ${{ secrets.SENKO_REGISTRY_TOKEN }}
      - run : |
          docker build -t ghcr.io/sokkuri/phantom-client:${{ github.sha }} .
          docker push ghcr.io/sokkuri/phantom-client:${{ github.sha }}
